name: document_camera_frame
description: Flutter package for capturing and cropping document images with a customizable camera interface.
version: 2.0.4
homepage: https://github.com/ahmedzein-dev/document_camera_frame
issue_tracker: https://github.com/ahmedzein-dev/document_camera_frame/issues

topics:
  - camera
  - document
  - cropping
  - scanner
  - ocr

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image: ^4.5.4
  camera: ^0.11.2
  #path_provider: ^2.1.5
  path_provider: ^2.1.4
  #flutter_animate: ^4.5.2
  flutter_animate: ^4.5.0
  google_mlkit_object_detection: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
